spring.application.name=career-assessment-backend
spring.datasource.url=jdbc:mysql://localhost:3306/futureforge
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pavanikolavennu16@gmail.com
spring.mail.password=bvle acuq tgrn ytvi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=MySuperSecureJwtSecretKey1234567890123456
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,https://future-forge.vercel.app